### ISSUE TITLE
Return value of the execute method in qiskit classes

### ISSUE THREAD

**Issue by cDenius** [cirKITers/Quafel#10]
I think the ```execute()``` method should return the result (meaning measurement results) in every class. But in the ```duration_real```class we return the time and in ```duration_qiskit```we return nothing. 

To use the fact that qiskit measures the time on its own, we might want to save the `result` object of the last run and then reuse it in ```time_measurement```.

Something like this:

```python

class duration_real(duration_qiskit):

...

    def execute(self, shots):
        if self.qcs.__len__() == 0:
            return None
        result = q.execute(self.qcs, backend=self.backend, shots=shots).result()
        self.last_result = result

        return result.get_counts()    

    def time_measurement(self, shots):
        self.execute(shots)
        return self.last_result._metadata["time_taken"]

```

Not sure if this is valid qiskit code and it also feels a little bit hacky. But just as a start of discussion.

**Comment by stroblme** [comment]
Agree, your proposed solution sounds good, although I'm feeling a bit unhappy about introducing a state variable.
However, it's still more consistent than the current implementation and should be easy to adapt if sth. changes in the future.

**Comment by cDenius** [comment]
Yes, the state variable is not nice. 

Another possibility would be:

```python

class duration_real(duration_qiskit):

...

    def execute(self, shots, full_results=False):
        if self.qcs.__len__() == 0:
            return None
        result = q.execute(self.qcs, backend=self.backend, shots=shots).result()

        if full_results:
            return results
        return result.get_counts()    

    def time_measurement(self, shots):
        results = self.execute(shots, full_results=True)
        return results._metadata["time_taken"]

```

So we override ```execute()``` but with an additional argument. The default case still gives us the expected result of only the measurements. But also far from perfect.
